### ISSUE TITLE
Remove the flags from language picker

### ISSUE THREAD

**Issue by toastal** [Sav22999/emoji#100]
Flags represent nations, not languages. It’s the wrong symbol and to be politically neutral (like the Unicode consortium is about not accepting any new flags) take them off the language picker. I appreciate (and chuckled) that you acknowledged that languages are spoken in more than one nation, but it's still incorrect as expats & immigrants can't identify, marginalized/minority groups feel left out, etc. It also becomes a reminder of colonialism–especially when you see that some Latin American nations are included for Spanish, but there are no African nations for French. Heck, English has massive speakers in India, Pakistan, Nigeria, and the Philippines but aren't represented.

This would be better with the 2 or 3-character language ISO code + the native language in its native script–with this native script being is a _great_ symbol for the language.

**Comment by Sav22999** [comment]
Great suggestion, thank you!
I'll remove those flags to avoid any problems 😉

**Comment by Sav22999** [comment]
#106
