### ISSUE TITLE
Better keyboard accessibility (allow use of arrow keys in search results)

### ISSUE THREAD

**Issue by SpitFire-666** [Sav22999/emoji#103]
Hi, I've set the addon to open with Ctrl+Shift+F.

I can then type in ```lol``` to find an emoji, then ```Enter``` to focus in the search results area 

![image](https://github.com/Sav22999/emoji/assets/38451588/e0fcafd9-5581-4616-b524-7bbcc8e841de)

Unfortunately the arrow keys don't work to navigate to other emojis, eg the lollipop or lolly.

Would you consider allowing us to use arrow keys to navigate the results pane? 

Also, I can't see a way to jump out of the search box to the emoji list via keyboard when the search field is empty:
![image](https://github.com/Sav22999/emoji/assets/38451588/55237620-cbbd-4dad-948e-2427a39b0e2e)

Cheers

**Comment by Sav22999** [comment]
To navigate via keyboard in the addon use the key "Tab" to go to the next element and "Shift+Tab" (or "Maiusc+Tab") to go to the previous element. This works always and in every section.

**Comment by Sav22999** [comment]
@SpitFire-666 I close this issue because it should be fixed, otherwise you can reopen it. I remain at your disposal, also on Telegram and via email.
