### ISSUE TITLE
Update "sick" search keyword to include more emojis

### ISSUE THREAD

**Issue by SpitFire-666** [Sav22999/emoji#104]
When typing in "sick", only one emoji comes up:

![image](https://github.com/Sav22999/emoji/assets/38451588/7c91db1e-79ad-434d-8f03-93fca299fb40)

Surprisingly, the built-in Win10 emoji picker is actually on point for once:

![image](https://github.com/Sav22999/emoji/assets/38451588/175949de-2e68-402b-b1f9-f75943b0be5b)

Just a small improvement, thanks!

**Comment by Sav22999** [comment]
#106
