### ISSUE TITLE
Add more keywords for bath/soap/sparkles

### ISSUE THREAD

**Issue by SpitFire-666** [Sav22999/emoji#110]
For example, _clean_, _tidy_ and _scrub_ return no emojis.

It would be nice if they brought up stuff like these
🛀✨🧼🧹

There could be others too.

Cheers

**Comment by Sav22999** [comment]
@SpitFire-666 Hi, thanks for your suggestion!

I'm constantly improving the addon, so if you want to contribute to improve it I ask to you to tell me the list of emojis and stuff to add 😄 

Thanks!
