### ISSUE TITLE
Please remove the popup for telegram stuff

### ISSUE THREAD

**Issue by imax9000** [Sav22999/emoji#114]
Sorry, it almost gave me a heart attack that you might be russian

**Comment by Sav22999** [comment]
@imax9000
Hi! First of all, I'm sorry about the inconvenience.
Then, Telegram is not Russian, it's created by a Russian – a good Russian, I would say – and it's free and open-source.

The add-on is free and open-source too, and it's inclusive. You can totally ignore it, just use "OK, hide" and you won't see it again

**Comment by imax9000** [comment]
Thanks that it should only show up once.

However, there's no such thing as "good russian". And especially not that particular one.
