### ISSUE TITLE
Add more keywords for hourglass(es) ⌛⏳

### ISSUE THREAD

**Issue by SpitFire-666** [Sav22999/emoji#121]
plz!

For example:
- I know them as "egg timers" - this brings up a hospital and an M mark only
- Searching for "timer" does not show the hourglass(es)
- Searching for "sand" brings up only one of the hourglasses
- Could also add the keyword "busy" = ⏳

Thanks again!

**Comment by Sav22999** [comment]
@SpitFire-666 Thank you for the feedback: I'll add more keywords in a future update. Stay tuned 😄 

If you find other emojis with 'a few' keywords, please open another issue and report them there. Thanks!
