### ISSUE TITLE
RFC: Enable Unicode 15 emojis  without Tweemoji support

### ISSUE THREAD

**Issue by marcosins** [Sav22999/emoji#129]
Release 3.18.1[^1] last year introduced support for all Unicode 15 emoji waiting for Tweemoji to support them but Tweemoji hasn't had a release for 2+ years[^2].

¿Can new emojis be enabled anyway?

[^1]: https://github.com/Sav22999/emoji/releases/tag/3.18.1
[^2]: https://github.com/twitter/twemoji/releases

**Comment by Sav22999** [comment]
@marcosins you're totally right, in fact I'm thinking to remove Twemoji (or, at least, not use it as default :( )

In the beta branch you can see I've already added new emojis, and I'll add more

Thanks for the feedback

**Comment by Sav22999** [comment]
@marcosins you'll find in the latest release (3.23) the new emojis!

In addition, in the 3.23.1 you'll find the new emojis (standard Emoji 15.1) also for Twemoji!

**Comment by marcosins** [comment]
Thank you
