### ISSUE TITLE
Feature request: Emoji sequence option

### ISSUE THREAD

**Issue by PeopleInside** [Sav22999/emoji#15]
Hi, thank you for this extension, I use in Firefox but after try in Chrome [Emoji Keyboard by JoyPixels®](https://chrome.google.com/webstore/detail/emoji-keyboard-by-joypixe/ipdjnhgkpapgippgcgkfcbpdpcgifncb) I feel I'm missing the opportunity to select and copy in memory more than one emoji.

For example I need insert more than one emoji in a message like:

Merry Christmas 🎄⭐🎁

I need click on the extension, on the emoji, on GitHub, paste and do this for every emoticons.
It will be nice to choose to select this three emoji than paste in one time.

**Comment by Sav22999** [comment]
@PeopleInside Yes, exactly. For now you have to click to every emoji and paste it, singularly.

I'll try to implement a feature which permits you to select more then one emoji, but it's not the primary purpose of this addon.

Thanks for the feedback/suggestion 😄

**Comment by PeopleInside** [comment]
Will be awesome!
Thank you very much, have a great holidays! 🎄⭐🎁 (need click three times) ahaha 😃

**Comment by Sav22999** [comment]
@PeopleInside As you required, I've implemented the "Multi-copy" feature. You should be able to turn on in Settings.
It's very useful, you're right!!!

It's already available on Firefox Addons (3.8), but not yet on Chrome Web Store and Edge Addons (because Google and Microsoft, respectively, need to approve edits before to publish them).

Enjoy!

**Comment by PeopleInside** [comment]
Wow thank you very much! Very fast and happy you find useful too!

Happy Holidays!

**Comment by PeopleInside** [comment]
Do you know how can I install before is updated on Firefox? Download the zip but Firefox never accept for install.

**Comment by Sav22999** [comment]
@PeopleInside Firefox has already updated the addon.
Try to check for update manually: in "Addons" (about:addons):
![image](https://user-images.githubusercontent.com/32335378/103099942-b8df6000-4610-11eb-959d-7bbdf602129a.png)

**Comment by PeopleInside** [comment]
I need remove and reinstall now Firefox show I have 3.8 but I cannot see any settings to allow multi-copy and to use the new function.

![SharedScreenshot](https://user-images.githubusercontent.com/5006150/103100115-81bd7e80-4611-11eb-8750-7bffa166d7e5.jpg)

**Comment by Sav22999** [comment]
@PeopleInside In the screenshot there is the option "Multi-copy", it's set at "No", you need to switch to "Yes" and then Save settings
