### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by sandornagy517** [Sav22999/emoji#19]
I think it would be awesome to have optional keyboard support. 

Opening the keyboard as a popup with a key combitnation like **ALT+SHIFT+E** or maybe even have it optional in settings.

Once the keyboard is open with the **key combo** it should automatically focus the search field and then once a keyword was typed in and enter was pressed **the focus should go to the emojis** and once enter was pressed on an emoji the emoji should be **copied to clipboard and the keyboard should close** retrieving the focus to the element which was focused before the emoji keyboard was opened

**Comment by Sav22999** [comment]
Related to #20
