### ISSUE TITLE
Keyboard support

### ISSUE THREAD

**Issue by lacexd** [Sav22999/emoji#20]
I think it would be awesome to have optional keyboard support.

Opening the keyboard as a popup with a key combitnation like ALT+SHIFT+E or maybe even have it optional in settings.

Once the keyboard is open with the key combo it should automatically focus the search field and then once a keyword was typed in and enter was pressed the focus should go to the emojis and once enter was pressed on an emoji the emoji should be copied to clipboard and the keyboard should close retrieving the focus to the element which was focused before the emoji keyboard was opened

**Comment by Sav22999** [comment]
@sandornagy517 the shortcut customisable it's a bit complicated. It's in the "manifest.json" and so it's more complicated customise it.

Alt+Shift+E open the Firefox menu (Alt+E)... I don't think it's possible the combination "Alt+Shift" actually.

For the focus, in the 3.9.1 works in that way!
When you open the add-on the searchbox get the focus. When you digit/type the keyword the focus remain to the searchbox, until you press "Enter" in your keyboard, so the add-on give the focus to the emojis.

If you want to auto-close the popup, you need to enable it in Settings (and, after emoji is copied, the focus go back to the textbox in web browser).
