### ISSUE TITLE
Non emoji - emoji like ☻, ♞, ...

### ISSUE THREAD

**Issue by daholzfeind** [Sav22999/emoji#24]
There are a few emojis, to be more precise non-emojis, out there, e.g. ☻ or ♞ , that do have emojis on distinct platforms, but not on all platforms. Should these be also part of the emoji - picker? 

See https://emojipedia.org/black-smiling-face/ for the Unicode sidenote.

**Comment by Sav22999** [comment]
@daholzfeind Hi! Thanks for the reporting.

Do you think they are necessarily?
I don't really like them (also because it more like "character" than "emoji").

**Comment by Sav22999** [comment]
@daholzfeind I close this issue because I haven't received a reply for 24 days.
In case you can reopen this in future :smile:

**Comment by daholzfeind** [comment]
@Sav22999 First, sorry for my late response. Thank you for your remarks. I see your point. Sometimes I use this one ☻ on my Samsung device. I did not find it in the emoji picker, that's the reason why I opened the issue. But since they are not supported on all platforms it makes no sense to add them, you're right. 🙂
