### ISSUE TITLE
There is one additional column when I choose the emoji size "small"

### ISSUE THREAD

**Issue by pandark** [Sav22999/emoji#25]
When I pick "Small" as "Emoji size" in the settings, there is one more column displayed than the number I pick as "Columns" (the minimum number of columns displayed is therefor 9 instead of 8).
The number of columns displayed when I pick any other size is correct.

**Comment by Sav22999** [comment]
I'll check, thank you :D

**Comment by Sav22999** [comment]
I've just fixed the bug, I've published the new release with the fix :smile:
Thanks again for the report

**Comment by pandark** [comment]
Wow, that was fast! :open_mouth: 
:+1:
