### ISSUE TITLE
Feature request: ability to change the extension's emoji on the toolbar

### ISSUE THREAD

**Issue by blakegearin** [Sav22999/emoji#26]
I often have to take screenshots on my computer for work and the 😛 emoji is a bit much. Being able to change it out for something else would be much appreciated

**Comment by Sav22999** [comment]
Sorry, what do you mean? You would customise the icon of the extension? 😃 

In that case, I'll see to implement it (choosing from a list of icons), in a future update, thanks!

**Comment by Sav22999** [comment]
@blakegearin Added :smile:
