### ISSUE TITLE
Code Improvement Suggestions

### ISSUE THREAD

**Issue by erosman** [Sav22999/emoji#27]
Only a suggestion ....

For example.. consider the following:

https://github.com/Sav22999/emoji/blob/d5ea4fb95e735c0f537e4cdb0d679483931f8658/js/script.js#L982-L1004

- There is no need to get the same item multiple times & create extra load
- `classList.remove` can remove multiple items

e.g.

```js
function setFontFamily() {

  document.querySelectorAll('#emojis', '#titles', '#top-section').forEach(item => {
    item.classList.remove('font-twemoji', 'font-notocoloremoji','font-openmojicolor','font-openmojiblack','font-default');
    item.classList.add('font-' + font_family);
  }):
} 
```

If the aim it to reset all styles from an item then the following will do the job more efficiently:
```js
item.className = 'font-' + font_family;
```

In fact, above elements are static and `document.getElementById("emojis")` is used 15 times. It can be cached to avoid traversing the DOM each time e.g.
```js
const emojis = document.getElementById('emojis');
const titles = document.getElementById('titles');
const top_section = document.getElementById('top-section');
```

Considering all above, here is another example:
```js
// global 
const emojis = document.getElementById('emojis');
const titles = document.getElementById('titles');
const top_section = document.getElementById('top-section');


function setFontFamily() {

  [emojis, titles, top_section].forEach(item => item.className = 'font-' + font_family):
} 
```

Another suggestion ....

https://github.com/Sav22999/emoji/blob/d5ea4fb95e735c0f537e4cdb0d679483931f8658/js/script.js#L1116-L1130

Details of the actions:

- `document.getElementsByClassName("extension-icon-button")[0]`
  - Traverse the DOM from the start to end
  - Find all node with above class
  - only select the first one
  - leave the rest
- `document.getElementsByClassName("extension-icon-button")[1]`
  - Traverse the DOM from the start to end AGAIN
  - Find all node with above class AGAIN
  - only select the 2nd one
  - leave the rest AGAIN
- `document.getElementsByClassName("extension-icon-button")[2]`
  - Traverse the DOM from the start to end AGAIN
  - Find all node with above class AGAIN
  - only select the 3rd one
  - leave the rest AGAIN
- .... etc

Above can be performed more efficiently like the following:

```js
function selectExtensionIconButton(index) {
  document.getElementsByClassName("extension-icon-button").forEach((item, idx) => {
    item.classList.remove("skin-tone-button-selected");
    idx == index && .classList.add("skin-tone-button-selected");
  });
}
```

Note: Although `getElementsByClassName()` is slightly (milliseconds) faster than `querySelectorAll()`, personally I would suggest using `querySelectorAll()` since it is more versatile and it returns nodeList while `getElementsByClassName()` returns **live** HTMLCollection which can lead to unexpected loops and results if not careful. Therefore ....

```js
function selectExtensionIconButton(index) {
  document.querySelectorAll('.extension-icon-button.).forEach((item, idx) => {
    item.classList.remove('skin-tone-button-selected');
    idx == index && .classList.add('skin-tone-button-selected');
  });
}
```

These are only some suggestions that can be applied to the rest of the code as well.

Note: `textContent` is many times faster than `innerHTML` and would also avoid AMO validator warning. 

For clearing element content (everything including other nodes):
```js
element.textContent = '';
```

For setting text only:
```js
element.textContent = 'Maybe another time';
```

**Comment by Sav22999** [comment]
Thanks for these suggestions, I'll see to implement some of those later :)

**Comment by Sav22999** [comment]
@erosman I've implemented some suggestions, thank you.
About "textContent" and "innerHTML" it's true, but the first time is not interpreted as HTML, but as text (instead, when I set the innerHTML I use always HTML).
