### ISSUE TITLE
Choose emoji via right-click

### ISSUE THREAD

**Issue by aronmgv** [Sav22999/emoji#29]
Hello,

I would like to suggest additional option for the emoji selection.

It would be to go through the right-click context menu:
1) User clicks right mouse button in the given input box on the page
2) There will be emoji button which will provide pop-up for emoji selection
3) Pop-up won't disappear until user clicks outside - so multiple emojis can be entered at once

Perhaps you can add option for the keyboard shortcut which would trigger this pop-up and it will bind with the active input (where mouse is in). If no active input is selected, open emojis from the ribbon location.

This will save so much time and unify it across multiple chats on the web.

What do you think? Appreciate your time on this. Michal

**Comment by Sav22999** [comment]
@MacGyver27 really really thanks for you feedback.
I'll think about it, but probably it's too complicated to implement.

**Comment by MacGyver27** [comment]
Thanks for your response. I understand the concept - hopefully it wont be too much hassle to grasp it. I definitely remember similar emoji plugin doing this. I believe it is this [one](https://addons.mozilla.org/en-US/firefox/addon/emoji-box/).
Thanks a lot. Michal

**Comment by Sav22999** [comment]
@MacGyver27 yes, I've understood the concept.
I do my best to improve the experience with the add-on and I'll try to improve, but I can't promise to add this feature, sorry.

**Comment by MacGyver27** [comment]
No problem at all. Glad you even consider it. Thanks!

**Comment by Cwpute** [comment]
Too bad this is not planned. It's actively the only option that prevents me from using it over EmojiBox (https://addons.mozilla.org/fr/firefox/addon/emoji-box/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org), which is outdated regarding the emojis available, but still provides this function.

**Comment by Sav22999** [comment]
@Cwpute Thank you for your suggestion. I'm thinking to plan this feature for the future ☺️

Continue to stay updated 🤙😉
