### ISSUE TITLE
Full keyboard navigation ?

### ISSUE THREAD

**Issue by edouard-lopez** [Sav22999/emoji#37]
Hello,
Thanks for the addon, it's lovely.

Here is my use case:
I usually don't know the exact name of the emoji I want to insert and use this extension to filter and narrow to 4-5 emoji then pick the one I want.

### Issue
Currently I use the shortcut to open the pop-in but then I need to switch to the mouse which break my keyboard-oriented workflow. Otherwise I have to hit TAB key more than a dozen time just to reach the list of emoji

### Solution
A solution would be to focus the list of emoji after the search input

**Comment by Sav22999** [comment]
When you finish to search just press "Enter" the emoji section should be automatically focused. Please, tell me if it doesn't work for you 😀
