### ISSUE TITLE
keyboard shortcut not working

### ISSUE THREAD

**Issue by aspieln3r** [Sav22999/emoji#43]
OS: archlinux
DE: KDE Plasma
Firefox 93
ctrl+alt+a is not working on my system

**Comment by aspieln3r** [comment]
I'll add more info if needed

**Comment by aspieln3r** [comment]
It is not a system shortcut if I check KDE settings. Any way to change and test different key combos?

**Comment by Marsup** [comment]
It was for me. As soon as I disabled the system shortcut, it worked.
![image](https://user-images.githubusercontent.com/796194/146640703-66fc2838-af07-4490-8541-224add90ca26.png)

**Comment by aspieln3r** [comment]
That worked. Thanks. I searched for the keycombo too initially but couldnt find it. Might have been some spelling mistake.
