### ISSUE TITLE
add on icon

### ISSUE THREAD

**Issue by Nis3r** [Sav22999/emoji#46]
It would be nice to be able to select any emoji for the icon

**Comment by aricooperdavis** [comment]
I think the suggestion is that they want to be able to use *any* icon for the extension rather than the preselected 11 options in the current settings menu.

**Comment by Sav22999** [comment]
@aricooperdavis oh, it makes sense but it's a bit useless (and it would be less lightweight because of every icon is an image, so I should add all emoji as image). Sorry
😥

**Comment by Nis3r** [comment]
Sorry I missed your response! I was helping my mom set it up and she wanted a little cat so I thought I'd ask. I get why it's not doable though! Thanks for the plugin use it most days! 😃
