### ISSUE TITLE
Unable to get emoticon directly from Chat window

### ISSUE THREAD

**Issue by ale5000-git** [Sav22999/emoji#49]
Hi,
I can copy from mail page and the paste here but I would like to open the emoticon menu directly from IRC chat windows inside Thunderbird.

Best regrads.

**Comment by Sav22999** [comment]
Hi @ale5000-git 
I guess you mean the Thunderbird version, right?

**Comment by ale5000-git** [comment]
Yes, sorry.
I didn't know that there was also a Firefox version.

**Comment by Sav22999** [comment]
@ale5000-git I don't know if it's possible actually 🤔 I'm sorry
