### ISSUE TITLE
"Insert a space between emojis" setting doesn't stick

### ISSUE THREAD

**Issue by silverwings15** [Sav22999/emoji#51]
Hi, on the latest version of the extension (3.13.7), the new setting "Insert a space between emojis" is reset to yes whenever you close the setting popup

**Comment by Sav22999** [comment]
@silverwings15 I've checked and it's true.
I'll fix it asap, sorry for the incovenience

**Comment by silverwings15** [comment]
works as expected now, thank you very much!
