### ISSUE TITLE
Setting for spaces not being saved?

### ISSUE THREAD

**Issue by Cpt-KeksMonster** [Sav22999/emoji#52]
In my case the setting whether there is a space between the emojis is always returning to the status "yes". Got this on multiple PCs. When I shutdown Firefox (e.g. rebooting the PC) the slider is back on "yes" although I have set it to "no", I don't want a space/blank to be added.

Is this a general problem? Or probably only a problem with my settings or other interfering add-ons?

**Comment by Sav22999** [comment]
What is the version of the addon?
I've already fixed this in the latest release

**Comment by Cpt-KeksMonster** [comment]
3.13.7.1 - Firefox is set to auto update all add-ons. Hmm. 🤔

**Comment by Sav22999** [comment]
This is weird 🤔

I'll check later, sorry for the inconvenience

**Comment by Cpt-KeksMonster** [comment]
Thanks a lot.

**Comment by Sav22999** [comment]
@Cpt-KeksMonster I've verified and the issue doesn't appears anymore in 3.13.7.1.
Could you try to restart Firefox? Maybe this can fix it 😄 🤔
