### ISSUE TITLE
Insert emoji doesn't work on Twitter

### ISSUE THREAD

**Issue by Sav22999** [Sav22999/emoji#54]

**Comment by marrws** [comment]
The extension looks for an `input` or `textarea` field but twitter uses a regular `div` with some js magic

Here's the code
https://github.com/Sav22999/emoji/blob/9494f09d4e1197c4507c8eb14f11e9834fc52415/js/emoji-insert-directly.js#L1-L9

**Comment by marcosins** [comment]
The extension looks for an `input` or `textarea` field but twitter uses a regular `div` with some js magic

Here's the code
https://github.com/Sav22999/emoji/blob/9494f09d4e1197c4507c8eb14f11e9834fc52415/js/emoji-insert-directly.js#L1-L9

**Comment by Sav22999** [comment]
Yeah, I know the code 😂😉
It's more important fix the problem with permissions for now

**Comment by Sav22999** [comment]
@marcosins No problems, absolutely.

I wanted just explain you I'm concentrating on that problem.

Do you have any ideas?

**Comment by vintotal** [comment]
I think direct insertion also does not work on Facebook messenger (messenger.com).

**Comment by marcosins** [comment]
same thing, they're not using a regular `<input>`, they use `<span>` + js magic:

```html
<p class="random-class-names" dir="ltr">
  <span data-lexical-text="true">this is not an input field</span>
</p>
```
