### ISSUE TITLE
Option to reduce padding in the emoji picker window

### ISSUE THREAD

**Issue by BlackGyver** [Sav22999/emoji#56]
Most of the visual real estate in the emoji picker window is used for (excessive) padding between emojis, I suggest a setting to control the amount of padding between emojis so we can have a more "compact" looking emoji picker.

**Comment by Sav22999** [comment]
@BlackGyver I understand what you mean... but actually the padding not influencing anything (in fact it's a fixed value, which could be also 0px). The important parameter is the size (width and height), which you can customise - already - in Settings 😄 

Thank you for the feedback!
