### ISSUE TITLE
Default shortcut open "Actions menu" on Linux Cinnamon

### ISSUE THREAD

**Issue by franklin-vidal** [Sav22999/emoji#57]
Hello, great extension.

I try to open with default shortcut but not working on Cinnamon.

**Comment by Sav22999** [comment]
@franklin-vidal Hi, maybe you're OS uses that shortcut for something else. Try to very shortcuts of the system 😊

**Comment by franklin-vidal** [comment]
Hello Saverio, thanks for answer.

Searching in the options of Cinnamon i don`t find this specific shortcut. There are a way to changing the source code for other shortcut? Changing these section in manifest.json?

 ```
 "commands": {
    "_execute_browser_action": {
      "suggested_key": {
        "windows": "Ctrl+Alt+A",
        "mac": "Command+Alt+A",
        "linux": "Ctrl+Alt+B",
        "default": "Ctrl+Alt+A"
      }
    }
  },
```

**Comment by Sav22999** [comment]
Yes, if you want to use directly the source code, you can change the shortcuts in manifest 👍😊

**Comment by franklin-vidal** [comment]
Great, it`s works now. Thanks. 🤗 ✌️‍
