### ISSUE TITLE
🪲 Poor clarity of copied characters

### ISSUE THREAD

**Issue by tetelevm** [Sav22999/emoji#59]
The original problem was that the "👍" + "number" sign was not displaying correctly.
I looked up the cause and saw that `"👍" -> '👍\u200d'`, which means that the joiner symbol is inserted after the icon symbol.
Then I looked in the source code, and the situation where the copied text ends in `\u200d`/`\ufe0f` is quite frequent (hundreds of pieces).
It would be good to fix this (I can fix it myself if needed). Also in pr I will correct the cleanliness of the descriptions in Russian (maybe in Ukrainian too).

**Comment by tetelevm** [comment]
The testcase is this:
Copy the "Thumbs Up Sign" symbol, paste it somewhere (like the github editor or sublime text), and then immediately write some number.
![изображение](https://user-images.githubusercontent.com/46541662/172594415-0cff355c-12bb-41cc-a243-3a55419eef49.png)
![изображение](https://user-images.githubusercontent.com/46541662/172594278-7b636235-1e2b-4464-9602-d31a4b97b54c.png)

**Comment by Sav22999** [comment]
@tetelevm please, specify the language you use the addon

**Comment by tetelevm** [comment]
Generally, I usually use Russian, but I just checked in English, Czech and Japanese and the problem is the same.
To better understand me, take a look at `master: /js/emojis.js :1471` (this is a description of the "Thumbs Up" symbol). What is the last character in the key? In my case it is `zero width joiner`, which is what causes the bug.
![изображение](https://user-images.githubusercontent.com/46541662/172623421-0b10a900-31b5-4501-a833-144b9ad16231.png)

**Comment by Sav22999** [comment]
@tetelevm Uh, I can't understand why there is that problem. Anyway, thanks for the report, I'll fix asap 😄

**Comment by tetelevm** [comment]
Ok)
So can I do pr with the improved Russian/Ukrainian translation?

**Comment by Sav22999** [comment]
It's not necessary the PR to improve Russian, because I use Crowdin for translations. Please, translate there 😄

**Comment by Sav22999** [comment]
@tetelevm it should be fixed in 3.14.2. Please, let me know if there are some other issues 😄
