### ISSUE TITLE
[I18N] Emoji names

### ISSUE THREAD

**Issue by meskobalazs** [Sav22999/emoji#64]
I am doing the translation for Hungarian for this project, and currently there are hundreds of emojis. I suggest reusing Unicode's CLDR data somehow, as the names are standardized by them, and frankly it makes more sense to reuse that data instead of manually translating that for lots of languages.

For example this is the current CLDR release: http://unicode.org/Public/cldr/latest
The folder `common/annotations` contains the localized names of emojis in `<language_code>.xml` files.

**Comment by Sav22999** [comment]
@meskobalazs hi!
Not all strings in my addon correspond to the unicode (sometimes there are many other strings, to improve the searching of the correct emoji)
