### ISSUE TITLE
🪲 Multicopying of letter emojis

### ISSUE THREAD

**Issue by tetelevm** [Sav22999/emoji#67]
Hi!
The addon has a multicopy emoji feature, and in general it works well:
🥦🥓🍓🥒🥘🥐🍄 (I copied 7 food emojis)

But when I copy the letters, this happens:
🇸🇼🇮🇹🇿🇪🇷🇱🇦🇳🇩
And in some applications it looks like this (i.e. it displays symbols of an unknown flag instead of letters)
![изображение](https://user-images.githubusercontent.com/46541662/186398614-e08443c3-fe2b-4f6b-974b-37b8f7312939.png)

But I copied the name of the proud independent country, not the flags (written with spaces):
🇸 🇼 🇮 🇹 🇿 🇪 🇷 🇱 🇦 🇳 🇩

Of course, this problem is related to the implementation of flags in the emoji, but any idea how to fix it? For example, maybe there's some emoji separation symbol that can be inserted after the letters when multicopying?

**Comment by Sav22999** [comment]
@tetelevm Hi, thanks for the issue.

Actually, letters in unicode are used to create flags. For this reason, if you want to copy only letter, without "rendering" the corresponding flag, please enable the option "Insert a space between emoji", and this issue should be fixed.

Please, let me know if it works 😄

**Comment by tetelevm** [comment]
@Sav22999 Oh, I didn't read the available settings carefully. Thanks for the advice 🙃
