### ISSUE TITLE
Typo in notification when removing emoji

### ISSUE THREAD

**Issue by acornestean** [Sav22999/emoji#71]
Description:
The Emoji extension allows users to remove emojis from a “most used emoji” list. After removing an emoji, a notification is displayed in the add-on pop-up, at the bottom, stating “removed correcly” instead of “removed correctly”.

Steps to reproduce:

1. Open the add-on dashboard by clicking on the add-on toolbar icon
2. Select any emoji category and click on an emoji. The emoji is copied to clipboard but also added to a “most used emoji” list (the tab with a clock icon)
3. Click on the “most used emoji” tab
4. Click on the “trash can” icon to initiate the removal of an emoji from the list and select the desired emoji.
5. Observe that the selected emoji will be removed from the list and a notification will be displayed confirming this operation
6. Notice the notification contains a typo. It states “removed correcly” instead of “removed correctly”.

Actual results:
The emoji removal notification contains a typo. It states “removed correcly” instead of “removed correctly”.

Expected results:
The emoji notification should state “removed correctly” when successfully removing an emoji from the list.

NOTE: Another source confirmed there is a typo in the add-on, in the default (English) locale: https://github.com/Sav22999/emoji/blob/689eda9186155365168c63c4817faa97a5d2b0f6/js/strings.js#L76
... and also the (unlocalized) versions for af-ZA, ca-ES, he-IL, hr-HR, it-IT, sr-SP, vi-VN, zh-TW

![2022-08-25_08h48_57](https://user-images.githubusercontent.com/50236075/188376527-eae38bfb-0b2c-48a2-a7c7-51adaf49098d.png)

**Comment by Sav22999** [comment]
@acornestean thank you!

**Comment by Rob--W** [comment]
FYI this typo is in more files. See https://bugzilla.mozilla.org/show_bug.cgi?id=1787100#c1 for the list of locales where the typo appears.

**Comment by Sav22999** [comment]
@Rob--W yeah, sure, but the localisation is in Crowdin, so in the next release I'll update in other languages as well.
Thanks! 😊😊
