### ISSUE TITLE
Unresponsive shortcut

### ISSUE THREAD

**Issue by xylographe** [Sav22999/emoji#73]
Pressing the shortcut `Ctl+Alt+A` doesn't open the add-on.
```
os = Win
ff = 102.3.0esr (32)
vs = 3.14.4.1
```

**Comment by haflaxa** [comment]
## +1

#### Issue
- Extension—_inconsistently_—fails to display the emoji picker after pressing corresponding kb shortcut.
- Behavior seems to only be triggered when the extension's icon is kept inside Firefox's **Overflow Menu**. 
- When emoji picker fails to display, the "More options..." icon (<sub><sup>**` 〉〉`**</sub></sup>) for Firefox's **Overflow Menu** gets highlighted instead.
- I'm able to trigger the issue less consistently when kb context it focused on a text input box. 

#### Minutiae
`OS`: **Linux — Fedora 36 (x86_64)**
`FF`: **105.0.1**
`VS`: **3.14.4.1**

**Comment by Sav22999** [comment]
@xylographe @haflaxa Hi! Thanks for reporting this.
I've verified and I cannot reproduce the bug.

Also in the icon is in the "Overflow menu", the add-on correctly open itself

Any other have this bug (in case, please, give me more info to reproduce it)
