### ISSUE TITLE
Overflow Menu inaccessibility

### ISSUE THREAD

**Issue by Neo-Qwerty** [Sav22999/emoji#75]
When this extension is pinned to the overflow menu in 'medium' emoji size, it cuts off before the 'delete from used emoji' & 'options' settings are available, latest Firefox build.
![image](https://user-images.githubusercontent.com/35006724/193825583-3d90fff0-92c0-40d2-86f5-70f73dacd50e.png)

Reducing the number of columns to 8 brought some of the 'delete' button back. 
![image](https://user-images.githubusercontent.com/35006724/193824067-71b06b57-8213-4953-abbc-1438613a9e5a.png)

Allowing users to set columns to 6 or 5 should make the options setting accessible from Overflow Menu mode without problems.

**Comment by Sav22999** [comment]
Cannot reproduce the bug
