### ISSUE TITLE
Support for Ubuntu's onscreen keyboard, Onboard, and/or on-screen keyboards in general for searching for emojis

### ISSUE THREAD

**Issue by mary-kate** [Sav22999/emoji#79]
Ubuntu and derivative distros come pre-packaged with the on-screen keyboard program called `Onboard`. It'd be great if you could search all the emojis with the Onboard keyboard. Right now, at least on a touchscreen-enabled device, tapping on the add-on's "Search for an emoji" field and then pressing on an on-screen keyboard button, no matter what key you might be pressing, instantly closes the emoji add-on menu.

**Comment by Sav22999** [comment]
@mary-kate Hi! I cannot avoid the popup of the emoji is closed, because it loses focus. For other addons you can search/use the onboard correctly?
