### ISSUE TITLE
Tooltips don't show in Thunderbird

### ISSUE THREAD

**Issue by tomasz1986** [Sav22999/emoji#80]
Please forgive me if this is a known problem or limitation. I've been using the add-on in Thunderbird for a few weeks and I like it the most among all the emoji pickers that are available for the program.

However, the main problem for me is that there are no tooltips with text labels for each emoji. As far as I understand, they should be displayed on mouse hover, but this doesn't seem to work, at least in Thunderbird.

I would be very grateful if you could check and possibly fix this problem (as not being able to understand the meaning behind each icon is a huge issue for those who aren't accustomed to them yet).

The Thunderbird version is the newest stable, i.e.

![image](https://user-images.githubusercontent.com/5626656/200842697-31e94ad1-69da-4325-b6f7-0b4a91e99c63.png)

and the OS is Windows 10 x86.

**Comment by Sav22999** [comment]
@tomasz1986 
For "tooltip" you mean the label which tell you what emoji is that? In that case, you don't need to click with the right-button of mouse... just wait some seconds on the emoji and the tooltip should be shown.

In case you want to insert a different emoji tone (only supported emojis, for example people emojis), in that case you need to click the right-button of the mouse.

I hope this can clarify you 😄

**Comment by tomasz1986** [comment]
> For "tooltip" you mean the label which tell you what emoji is that? In that case, you don't need to click with the right-button of mouse... just wait some seconds on the emoji and the tooltip should be shown.

Yeah, that's exactly what I'm trying to do. Unfortunately, nothing is shown even after waiting for a long time (e.g. 10+ seconds :confused:).

**Comment by Sav22999** [comment]
Oh, this is very weird... I cannot reproduce this bug 😕

**Comment by tomasz1986** [comment]
That's not good to hear 🙁. I'll try to test with a completely clean profile and report back what happens there.

**Comment by Sav22999** [comment]
@tomasz1986 
I got the same bug in Thunderbird right now... I don't know what's the problem... in Firefox it works correctly.
I'll think about something to show the tooltip or something else... stay tuned and my apologise for the inconvenience.

**Comment by tomasz1986** [comment]
For the time being, I've managed to hack around the code to show full labels on copy as follows.

`script.js`
```
        let spaceCharacter = " ";
        if (multi_copy == "no") {
            copyText = copyEmojiTemp + spaceCharacter + "(" + tooltip + ")";
        } else {
            if (space_emoji == "no") spaceCharacter = "";
            copyText = copyText + spaceCharacter + copyEmojiTemp + spaceCharacter + "(" + tooltip + ")";
        }
```

![image](https://user-images.githubusercontent.com/5626656/203824221-bb548678-9357-4d0a-9bfb-b64ddb4e2328.png)

May not be the prettiest, but it does the job 😉.

**Comment by Sav22999** [comment]
@tomasz1986 this is complicated and not too efficient because you can turn on the "multi copy" in Settings, and in that case this would be not usable

**Comment by Sav22999** [comment]
In the latest version (115) this issue there shouldn't be anymore

**Comment by tomasz1986** [comment]
Thanks! I can confirm the tooltips working in Thunderbird 115. However, now it seems that the settings menu doesn't work. Nothing happens when clicking on the cog icon 😢.

**Comment by Sav22999** [comment]
@tomasz1986 I'll check this problem, thanks! 😊

**Comment by Sav22999** [comment]
@tomasz1986 I've just checked and I don't get this issue. Try to check for the latest update of Thunderbird and the addon and let me know please
