### ISSUE TITLE
⚙️ missing

### ISSUE THREAD

**Issue by michel-thomas** [Sav22999/emoji#81]
I was looking for this one : ⚙️ (https://emojiterra.com/gear) but I don't find even if part of Unicode 4.1.
Have-I missed it in current set?

What is the current Unicode/Emoji version support?

Thanks for this great job!

**Comment by Sav22999** [comment]
@michel-thomas it's present. What release of Emoji do you use? In addition, you use it in a different language?
<img width="516" alt="image" src="https://user-images.githubusercontent.com/32335378/202724089-8db02a40-b1e7-4a5a-8654-d8fe2d0a9051.png">

**Comment by michel-thomas** [comment]
Release 3.14.6 in French

**Comment by Sav22999** [comment]
It's translated on Crowdin in this way: https://crowdin.com/translate/emoji-sav/75/en-fr?filter=basic&value=0#q=settings

In case, please, suggest a better translation

**Comment by michel-thomas** [comment]
Thanks. I suggest other translation.

**Comment by Sav22999** [comment]
I'll approve them asap ✌🏻
