### ISSUE TITLE
No Nazar Amulet

### ISSUE THREAD

**Issue by amandabee** [Sav22999/emoji#82]
I have tried every search term I can for the evil eye or nazar amulet (🧿 ) and I can't find it. I also looked at the other "Activity > Game" emojis and I don't see it there. 

![image](https://user-images.githubusercontent.com/150791/203425409-b18efc38-da9f-408c-803f-1cc2320c236c.png)

Other [Unicode 11](https://emojipedia.org/unicode-11.0/) emojis like 🦷 and 🦙 are in the add on. Is there a reason why the evil eye isn't in there?

**Comment by Sav22999** [comment]
@amandabee Hi, thanks for reporting me this.
I'm sorry to tell you're right, the 🧿 emoji is not present, but I'll add asap **thanks to you**!
If you find any other missing emojis, please report them here in GitHub 😄

**Comment by Sav22999** [comment]
Added 😄
