### ISSUE TITLE
Polish translation is all gibberish (yet approved) and Crowdin website unusable due to lag

### ISSUE THREAD

**Issue by tomasz1986** [Sav22999/emoji#83]
I'm very sorry if this is not the right place, but I'm trying to fix the Polish translation using Crowdin, yet there are at least two problems.

Firstly, the current translation is apparently at 97% and all the strings seem to be "approved", yet in reality the text is all gibberish. It looks as if the translation was done using Google Translate or worse. However, because the broken strings are marked "approved", it seems that each of my fixed translations need to be approved again.

Secondly, the Crowdin website is extremely sluggish. I assume the culprit is the `emojis.js` file being very large. This is a huge problem though, because I'm literally barely able to do any modifications, as every click or type requires to wait at least a few seconds for a response. I'm on a decent hardware too. Is there any other way to modify the strings to avoid dealing with the laggy website?

**Comment by Sav22999** [comment]
@tomasz1986 just open issues on Crowding and I'll approve and fix them

**Comment by Sav22999** [comment]
You can try to translate them offline (download the file) and then upload it 😄

**Comment by tomasz1986** [comment]
I've just done a test with local translation and upload a moment ago using a few strings. It seems they've now been added as additional translations as follows

![image](https://user-images.githubusercontent.com/5626656/205505321-acb851bb-f1cd-44e2-b908-c0e3cccd93df.png)

Is this the right method to proceed with the rest as well?

**Comment by Sav22999** [comment]
@tomasz1986 You need to open issues otherwise it's impossible for me find all new strings translated

**Comment by tomasz1986** [comment]
Yeah, that likely won't be possible, because I need to wait 5+ seconds for the site to respond after each click 🙁.

**Comment by Sav22999** [comment]
@tomasz1986 I've promoted you to Proofreader, so you should be able to approve translations by yourself 😄
