### ISSUE TITLE
So many men and women, so few persons

### ISSUE THREAD

**Issue by amandabee** [Sav22999/emoji#84]
I would swear that the current library includes a gender neutral "person" by default but in the add on I'm only seeing MAN JUGGLING 🤹🏻‍♂️ and WOMAN JUGGLING 🤹🏻‍♀️. No PERSON JUGGLING [🤹](https://emojipedia.org/person-juggling/) though. 

That seemed consistent across activities. That there were two options (MAN, WOMAN) doing the thing, but no neutral PERSON doing the thing.

**Comment by Sav22999** [comment]
@amandabee maybe it's true. I'll update asap with "Person" neutral as well 😊

**Comment by Sav22999** [comment]
@amandabee I've checked and actually is present the neutral ("Person") as well. Which language don't you find those emojis in? 😄

**Comment by amandabee** [comment]
Weird. I am seeing them now. I would swear they were not there before.

**Comment by Sav22999** [comment]
@amandabee Can you see them now?

I've added all "Person" missing emojis, but if you find some other missing emojis, please open a new issue here. Thanks for reporting 😊
