### ISSUE TITLE
[Feature Request/Bug] Please add ability to disable Ctrl+Alt+A hotkey. 

### ISSUE THREAD

**Issue by fourteen-1** [Sav22999/emoji#90]
Ctrl+Alt+A is bringing up the emoji addon popup and there is no option to disable it. I have another function assigned to that hotkey combo and now that doesn't work anymore

Thank you!

**Comment by Sav22999** [comment]
@fourteen-1 Hi, I've added in the to-do list the customisation of keyboard shortcut to open popup, and also disable shortcut.

I'm working on it, so wait for it in a future update.
Thanks for the feedback 🥰

**Comment by Sav22999** [comment]
Implemented in #91 (3.16)
