### ISSUE TITLE
Add a monochrome extension icon option.

### ISSUE THREAD

**Issue by Draconicrose** [Sav22999/emoji#95]
The extension icon being a fully colored emoji is mildly annoying for my personal tastes. 
![image](https://user-images.githubusercontent.com/17189964/227724372-00ad5c7a-a066-45b5-965b-9b6ed0b347ea.png)
I would like to have a black and white/monochrome option like Awesome Emoji Picker (left) has.

**Comment by Sav22999** [comment]
Oh, sure, that's a fantastic feedback.
I've already release the version 3.17, so I'll add some new extension icon in the next release (maybe 3.17.1 😄)

Thanks
